# Copyright (c) 2026 Trustedwear Tech Private Limited (https://citra-ai.com)
# Author: Rohit Kumar Chandan
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0

"""The one picture at the top of the README.

The README currently spends 131 lines on the experiment near the top and 10
lines on what the product DOES, with "build an app, an API or an embedded UI"
buried at line 1443 -- 88% of the way down. A reader who stops after two
screens, which is most of them, sees a research write-up.

So this diagram carries the two claims that have to land before anything else,
side by side, because they are equal and the README has never treated them so:

  LEFT   Judgement compounds. A recommendation is made with its citation, an
         officer corrects it, agreement among officers turns that into a rule,
         and the next case uses it. This is the thing nothing else does.

  RIGHT  Describe it, and it builds. One sentence of plain English becomes a
         Decision App, an API, an embedded card or a dashboard -- over YOUR
         database, through an ontology generated by interviewing it.

Palette, fonts and primitives are imported from make_story_svgs rather than
copied: two files defining the same blue is how a light and a dark diagram
drift apart, and the existing eight already solved this.

    python scripts/make_hero_svg.py
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from make_story_svgs import THEMES, FONT, LICENCE, head, txt, box, arrow  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "assets" / "story"

W, H = 1240, 430
MID = 620          # the divider between the two panels


def _chip(x, y, w, s, t, tone="brand", size=12.5):
    """A small labelled pill. Used for the four build outputs."""
    fill = {"brand": t["brandSoft"], "good": t["goodSoft"], "warn": t["warnSoft"]}[tone]
    edge = {"brand": t["brand"], "good": t["good"], "warn": t["warn"]}[tone]
    ink = {"brand": t["brandDeep"], "good": t["good"], "warn": t["warn"]}[tone]
    return (box(x, y, w, 30, t, fill=fill, stroke=edge, r=15, sw=1.2)
            + txt(x + w / 2, y + 19.5, s, t, size=size, fill=ink,
                  weight="600", anchor="middle"))


def _panel_title(x, y, kicker, title, t):
    return (txt(x, y, kicker, t, size=11.5, fill=t["faint"], weight="700")
            + txt(x, y + 26, title, t, size=20, fill=t["ink"], weight="700"))


def hero(t: dict) -> str:
    s = head(W, H, "Citra Decision System: judgement compounds, and you build "
                   "apps, APIs and embedded UI by describing them", t)

    # ---------------------------------------------------------------- divider
    s += (f'<line x1="{MID}" y1="34" x2="{MID}" y2="{H-30}" '
          f'stroke="{t["line"]}" stroke-width="1" stroke-dasharray="3 5"/>\n')

    # ============================================================ LEFT PANEL
    s += _panel_title(40, 44, "IT LEARNS FROM YOUR PEOPLE",
                      "Judgement compounds", t)

    ry = 122          # row baseline for the loop
    bw, bh = 116, 62

    # case -> recommendation -> correction
    s += box(40, ry, bw, bh, t, fill=t["panel"], stroke=t["panelEdge"])
    s += txt(98, ry + 27, "A case", t, size=14, fill=t["ink"], weight="600", anchor="middle")
    s += txt(98, ry + 45, "arrives", t, size=12.5, fill=t["mute"], anchor="middle")
    s += arrow(160, ry + bh / 2, 196, ry + bh / 2, t)

    s += box(198, ry, 148, bh, t, fill=t["brandSoft"], stroke=t["brand"])
    s += txt(272, ry + 24, "Recommendation", t, size=14, fill=t["brandDeep"],
             weight="700", anchor="middle")
    s += txt(272, ry + 42, "with its citation", t, size=12, fill=t["brandDeep"], anchor="middle")
    s += arrow(350, ry + bh / 2, 386, ry + bh / 2, t)

    s += box(388, ry, 148, bh, t, fill=t["warnSoft"], stroke=t["warn"])
    s += txt(462, ry + 24, "An officer", t, size=14, fill=t["warn"],
             weight="700", anchor="middle")
    s += txt(462, ry + 42, "corrects it", t, size=12.5, fill=t["warn"], anchor="middle")

    # agreement -> rule
    ay = 236
    s += (f'<path d="M462 {ry+bh} L462 {ay-10}" stroke="{t["line"]}" '
          f'stroke-width="1.5" fill="none" marker-end="url(#a)"/>\n')
    s += txt(474, ay - 22, "three officers agree", t, size=12, fill=t["faint"])

    s += box(300, ay, 236, 58, t, fill=t["goodSoft"], stroke=t["good"])
    s += txt(418, ay + 24, "becomes a rule", t, size=14.5, fill=t["good"],
             weight="700", anchor="middle")
    s += txt(418, ay + 42, "written down, cited, reversible", t, size=11.5,
             fill=t["good"], anchor="middle")

    # rule feeds the next case
    s += (f'<path d="M300 {ay+29} L98 {ay+29} L98 {ry+bh+8}" '
          f'stroke="{t["good"]}" stroke-width="1.6" fill="none" '
          f'stroke-dasharray="5 4" marker-end="url(#ab)"/>\n')
    s += txt(112, ay + 12, "the next case uses it", t, size=12, fill=t["good"], weight="600")

    s += txt(40, 356, "Nothing is learned from a single opinion.", t,
             size=13, fill=t["mute"])
    s += txt(40, 376, "Agreement is the bar, and every rule says who set it.", t,
             size=13, fill=t["mute"])

    # =========================================================== RIGHT PANEL
    x0 = MID + 40
    s += _panel_title(x0, 44, "AND YOU BUILD IT BY DESCRIBING IT",
                      "Describe it, and it builds", t)

    # the sentence
    s += box(x0, 108, 520, 52, t, fill=t["panel"], stroke=t["panelEdge"])
    s += txt(x0 + 16, 132, "“Triage motor claims: flag anything over ₹5 lakh", t,
             size=13.5, fill=t["ink"])
    s += txt(x0 + 16, 150, "  or a repeat claimant, and say why.”", t,
             size=13.5, fill=t["ink"])

    # One sentence FANS OUT to four outputs -- a single arrow down the middle
    # landed on whichever chip happened to sit there and read as
    # "sentence -> Embedded UI -> database", which is not the claim.
    cy = 196
    centres = [x0 + 61, x0 + 178, x0 + 308, x0 + 456]
    bus_l, bus_r = centres[0], centres[-1]

    s += (f'<path d="M{x0+260} 162 L{x0+260} 178" stroke="{t["brand"]}" '
          f'stroke-width="1.6" fill="none"/>\n')
    s += (f'<path d="M{bus_l} 178 L{bus_r} 178" stroke="{t["brand"]}" '
          f'stroke-width="1.6" fill="none"/>\n')
    for c in centres:
        s += (f'<path d="M{c} 178 L{c} {cy-8}" stroke="{t["brand"]}" '
              f'stroke-width="1.6" fill="none" marker-end="url(#ab)"/>\n')

    # the four outputs
    s += _chip(x0, cy, 122, "Decision App", t, "brand")
    s += _chip(x0 + 132, cy, 92, "API", t, "brand")
    s += _chip(x0 + 234, cy, 148, "Embedded UI", t, "brand")
    s += _chip(x0 + 392, cy, 128, "Dashboard", t, "brand")

    # ...and all four collect back onto the one database
    for c in centres:
        s += (f'<path d="M{c} {cy+30} L{c} {cy+46}" stroke="{t["brand"]}" '
              f'stroke-width="1.6" fill="none"/>\n')
    s += (f'<path d="M{bus_l} {cy+46} L{bus_r} {cy+46}" stroke="{t["brand"]}" '
          f'stroke-width="1.6" fill="none"/>\n')
    s += (f'<path d="M{x0+260} {cy+46} L{x0+260} {cy+60}" stroke="{t["brand"]}" '
          f'stroke-width="1.6" fill="none" marker-end="url(#ab)"/>\n')

    # your data + ontology
    dy = 258
    s += box(x0, dy, 520, 74, t, fill=t["brandSoft"], stroke=t["brand"])
    s += txt(x0 + 260, dy + 25, "your database, described once", t, size=14.5,
             fill=t["brandDeep"], weight="700", anchor="middle")
    s += txt(x0 + 260, dy + 46, "point it at one you have, or stand a new one up —", t,
             size=12, fill=t["brandDeep"], anchor="middle")
    s += txt(x0 + 260, dy + 62, "`make ontology` interviews it and writes the rulebook", t,
             size=12, fill=t["brandDeep"], anchor="middle")

    s += txt(x0, 356, "Claims triage · loan origination · asset-quality review ·", t,
             size=13, fill=t["mute"])
    s += txt(x0, 376, "grievance routing · an operations dashboard.", t,
             size=13, fill=t["mute"])

    s += "</svg>\n"
    return s


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for theme, t in THEMES.items():
        p = OUT / f"0-hero-{theme}.svg"
        p.write_text(LICENCE + hero(t), encoding="utf-8", newline="\n")
        print(f"  {p.relative_to(OUT.parent.parent)}  ({p.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
