#!/usr/bin/env python3
"""Generate schema/sources.schema.json from registry_models.py.

The JSON Schema is GENERATED, never hand-edited. registry_models.py is the single
source of truth; two hand-maintained definitions is exactly the drift this whole
exercise exists to remove (my own hand-written `_KNOWN_SOURCE_KEYS` list in
router.py had that wart before this replaced it).

Usage:
    python gen_sources_schema.py            # write the file
    python gen_sources_schema.py --check    # exit 1 if it's stale (CI)

What the schema file covers: structure, types, enums, required fields, and
unknown keys. What it does NOT cover: the cross-field rules (mongodb needs
connection.collection; semantic needs rag.milvus_collection; fraud needs a PK).
Those are pydantic validators, and pydantic validators do not export to JSON
Schema. They are enforced by validate_sources.py and at MCP boot. So the file is
the EDITOR contract (autocomplete + live structural validation); the CLI is the
authoritative gate. That split is deliberate — the alternative is hand-writing
if/then JSON Schema that drifts from the code within a release.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

SCHEMA_PATH = pathlib.Path(__file__).parent / "schema" / "sources.schema.json"

_HEADER = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://citra-ai.com/schema/sources.schema.json",
    "title": "Citra dept-MCP sources.json",
    "description": (
        "The source registry a dept-MCP loads (SOURCES_FILE / SOURCES_JSON). "
        "GENERATED from source-mcp-template/registry_models.py by "
        "gen_sources_schema.py — do not edit by hand; your change will be "
        "overwritten and CI will fail. Authoring guide: docs/sources-file.md. "
        "This schema covers structure/types/enums/unknown-keys; cross-field "
        "rules (mongodb->collection, semantic->rag, fraud->primary key) are "
        "enforced by validate_sources.py and at MCP boot."
    ),
}


def build() -> dict:
    from registry_models import SourcesFile

    schema = SourcesFile.model_json_schema(
        ref_template="#/$defs/{model}",
        mode="validation",
    )
    # Put our identity first, then whatever pydantic produced. pydantic emits its
    # own $schema-less root; we prepend the draft + $id so editors bind to it.
    out = dict(_HEADER)
    for k, v in schema.items():
        if k in ("title", "description"):
            continue  # ours are better than the RootModel's autogenerated ones
        out[k] = v
    return out


def render(schema: dict) -> str:
    # Stable formatting so the --check diff is meaningful and reviewable.
    return json.dumps(schema, indent=2, sort_keys=False, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed schema is stale (CI drift gate)")
    args = ap.parse_args()

    rendered = render(build())

    if args.check:
        if not SCHEMA_PATH.exists():
            print(f"MISSING: {SCHEMA_PATH} — run: python gen_sources_schema.py",
                  file=sys.stderr)
            return 1
        current = SCHEMA_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"STALE: {SCHEMA_PATH} no longer matches registry_models.py.\n"
                f"The schema is generated — regenerate it:\n"
                f"    python gen_sources_schema.py",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {SCHEMA_PATH.name} matches registry_models.py")
        return 0

    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {SCHEMA_PATH} ({len(rendered):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
