// GENERATED from models.ICON_NAMES (smart-app-service/models.py) — keep the
// two lists in sync; publish rule I-01 rejects names outside that set, and
// tsc fails here on a name lucide does not export. Static named imports keep
// the bundle tree-shaken (the full lucide map would defeat it).
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Award,
  Banknote,
  BarChart3,
  BatteryCharging,
  Bell,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  Check,
  CheckCircle,
  CircleDollarSign,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coins,
  Compass,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Droplets,
  Eye,
  Factory,
  FileCheck,
  FileSearch,
  FileText,
  FileWarning,
  Filter,
  Flag,
  Flame,
  FolderOpen,
  Gauge,
  Gavel,
  Globe,
  Hammer,
  HardHat,
  HeartPulse,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Landmark,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Monitor,
  Package,
  Paperclip,
  PauseCircle,
  Percent,
  Phone,
  PieChart,
  PiggyBank,
  PlayCircle,
  Plug,
  PlugZap,
  Receipt,
  RefreshCw,
  Route,
  Scale,
  ScanLine,
  Search,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Sparkles,
  Star,
  Sun,
  Table,
  Tag,
  Target,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  TrafficCone,
  TrendingDown,
  TrendingUp,
  Truck,
  Upload,
  User,
  UserCheck,
  Users,
  Wallet,
  Wrench,
  XCircle,
  Zap,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "activity": Activity,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "archive": Archive,
  "arrow-down": ArrowDown,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "award": Award,
  "banknote": Banknote,
  "bar-chart-3": BarChart3,
  "battery-charging": BatteryCharging,
  "bell": Bell,
  "book-open": BookOpen,
  "briefcase": Briefcase,
  "building": Building,
  "building-2": Building2,
  "calendar": Calendar,
  "calendar-check": CalendarCheck,
  "calendar-clock": CalendarClock,
  "camera": Camera,
  "check": Check,
  "check-circle": CheckCircle,
  "circle-dollar-sign": CircleDollarSign,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "coins": Coins,
  "compass": Compass,
  "credit-card": CreditCard,
  "database": Database,
  "dollar-sign": DollarSign,
  "download": Download,
  "droplets": Droplets,
  "eye": Eye,
  "factory": Factory,
  "file-check": FileCheck,
  "file-search": FileSearch,
  "file-text": FileText,
  "file-warning": FileWarning,
  "filter": Filter,
  "flag": Flag,
  "flame": Flame,
  "folder-open": FolderOpen,
  "gauge": Gauge,
  "gavel": Gavel,
  "globe": Globe,
  "hammer": Hammer,
  "hard-hat": HardHat,
  "heart-pulse": HeartPulse,
  "history": History,
  "home": Home,
  "image": Image,
  "inbox": Inbox,
  "info": Info,
  "key": Key,
  "landmark": Landmark,
  "layers": Layers,
  "layout-dashboard": LayoutDashboard,
  "lightbulb": Lightbulb,
  "line-chart": LineChart,
  "list-checks": ListChecks,
  "lock": Lock,
  "mail": Mail,
  "map": Map,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "monitor": Monitor,
  "package": Package,
  "paperclip": Paperclip,
  "pause-circle": PauseCircle,
  "percent": Percent,
  "phone": Phone,
  "pie-chart": PieChart,
  "piggy-bank": PiggyBank,
  "play-circle": PlayCircle,
  "plug": Plug,
  "plug-zap": PlugZap,
  "receipt": Receipt,
  "refresh-cw": RefreshCw,
  "route": Route,
  "scale": Scale,
  "scan-line": ScanLine,
  "search": Search,
  "send": Send,
  "settings": Settings,
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "siren": Siren,
  "sparkles": Sparkles,
  "star": Star,
  "sun": Sun,
  "table": Table,
  "tag": Tag,
  "target": Target,
  "thermometer": Thermometer,
  "thumbs-down": ThumbsDown,
  "thumbs-up": ThumbsUp,
  "timer": Timer,
  "traffic-cone": TrafficCone,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  "truck": Truck,
  "upload": Upload,
  "user": User,
  "user-check": UserCheck,
  "users": Users,
  "wallet": Wallet,
  "wrench": Wrench,
  "x-circle": XCircle,
  "zap": Zap,
};

/** Render a spec-declared icon by its kebab-case name. Unknown / absent name
 * renders NOTHING (publish already gates the vocabulary; a stale stored spec
 * must degrade to no-icon, never a broken glyph). */
export default function Icon({
  name,
  size = 15,
  className,
}: {
  name?: string | null;
  size?: number;
  className?: string;
}) {
  const C = name ? ICONS[name] : undefined;
  if (!C) return null;
  return <C size={size} className={className} aria-hidden="true" />;
}

export const ICON_NAMES = Object.keys(ICONS);
